pipeline {
    environment {
    registry = "akashkatakam/webapp-backend"
    registryCredential = 'dockerhub'
    }
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Building image') {
            steps{
                script {
                    commitId = sh(returnStdout: true, script: 'git rev-parse HEAD')
                    dockerImage = docker.build registry + ":$commitId"
                }
            }
        }
        stage('Deploy Image') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                    dockerImage.push()
                    }
                }
            }
        }
    }
}